### ISSUE TITLE
Compas, tenemos que hacer la selección del Libro!

### ISSUE THREAD

**Issue by Santiago-Jurado** [Colegio-Seminario-Diocesano/solucionario-1103#2]

**Comment by JohanP13** [comment]
Okey, que libros son opciones?

**Comment by Malevaro** [comment]
El calculo de tomas y el de stwart

**Comment by Santiago12-svg** [comment]
Con el de Thomas que hemos hecho muchos ejercicios ahí

**Comment by DiegoFer12** [comment]
Yo propongo el cálculo de Zill

**Comment by sebasalejo** [comment]
Yo propongo el cálculo de Thomas

**Comment by Santiago12-svg** [comment]
Thomas propongo yo también, se encuentra mucha variedad para el nivel de cada uno.

**Comment by Malevaro** [comment]
yo opino que el de Thomas también

**Comment by JohanP13** [comment]
okey concretaríamos el de tomas de una vez?

**Comment by Laura0906** [comment]
Si, Me parece

**Comment by Santiago-Jurado** [comment]
De uñas! Que sección sería entonces?

**Comment by DiegoFer12** [comment]
Cada uno escoge la sección verdad?

**Comment by Malevaro** [comment]
Siii

**Comment by Santiago12-svg** [comment]
Creo que si se puede elegir la sección y ejercicio que queramos

**Comment by JohanP13** [comment]
asignamos ejercicio por código para que no se repitan? o cada uno que elija?

**Comment by Santiago12-svg** [comment]
Cada uno

**Comment by Santiago12-svg** [comment]
Pues vea elijan un ejercicio desde ya y vayan asignando para no repetir

**Comment by DiegoFer12** [comment]
Si, esa ya es el siguiente punto del trabajo, cada quien crea su issue.

**Comment by Laura0906** [comment]
¿Creamos el Issue en orden de lista ? o Como vayamos haciendo

**Comment by sebasalejo** [comment]
En el orden que vayan llegando

**Comment by DiegoFer12** [comment]
Propongo que para nombrar las ramas fueran con el nombre de la persona, para mayor organización.

**Comment by Santiago12-svg** [comment]
@DiegoFer12 ¡buena idea!

**Comment by 1002460770** [comment]
MuchachoS yo considero que sacar los ejercicios de el libro de stwart

**Comment by JohanP13** [comment]
Entonces concretado el libro de tomas y estén pendientes que no se repitan los ejercicios

**Comment by Sergio17-2004** [comment]
Muchachxs, pienso que deberíamos trabajar en base al cálculo de Thomas.
